### ISSUE TITLE
Please remove requiring admin signature to be writable account

### ISSUE THREAD

**Issue by aankor** [QuarryProtocol/quarry#101]
It is not reflected in IDL and works only if admin is fee payer (because of unification of account attributes for the different occurrences of the same account)

https://github.com/QuarryProtocol/quarry/blob/6dc45e0c14b689982f940019599f3523d4287d86/programs/quarry-mint-wrapper/src/account_validators.rs#L112

**Comment by michaelhly** [comment]
cc @larrinator1
