### ISSUE TITLE
Request to update anchor to latest version in Cargo.toml

### ISSUE THREAD

**Issue by dshaw002** [QuarryProtocol/quarry#115]
I'm using quarry as a dependency for an anchor program which integrates with Quarry. I can't use the latest version of anchor due to a dependency conflict with the older version of anchor that Quarry currently uses. Screenshot attached.

<img width="773" alt="Screen Shot 2021-10-02 at 9 10 39 PM" src="https://user-images.githubusercontent.com/1524593/135736012-f021765f-f745-4d56-81b4-6fb82dd61533.png">

**Comment by michaelhly** [comment]
Please install the latest quarry release. Let us know if you still have issues.
