### ISSUE TITLE
Request to deploy to Testnet

### ISSUE THREAD

**Issue by jeffhu1** [QuarryProtocol/quarry#127]
Hi,

Currently the USDC faucet only exists on Testnet. Would it be possible to deploy an extra copy of the contracts to testnet so we can test it with the faucet? Otherwise we would need to set up another mock usdc mint faucet for devnet.

**Comment by larrinator1** [comment]
Hey @jeffhu1 -- I'm happy to do so. Will do soon!

**Comment by jeffhu1** [comment]
@larrinator1 sent!

**Comment by larrinator1** [comment]
Done! @jeffhu1
