### ISSUE TITLE
Withdraw delegation

### ISSUE THREAD

**Issue by halimabergaoui** [QuarryProtocol/quarry#345]
Hello, is there a way to delegate the withdraw signature right to a different account?

**Comment by larrinator1** [comment]
Hi @halimabergaoui -- what is the use case?

**Comment by halimabergaoui** [comment]
Hi @larrinator1, we are developing an automated trading and yield farming protocol. It can swap and stake tokens according to some given data. However, the user won't be signing these transactions. He will just delegate the tokens once then the protocol can trade it automatically.
