### ISSUE TITLE
error codes guide

### ISSUE THREAD

**Issue by halimabergaoui** [QuarryProtocol/quarry#399]
Hello, is there a guide for the error codes and messages? For example, what are the possible causes of the code 0xbc4.

![telegram-cloud-photo-size-4-5794254304050264889-x](https://user-images.githubusercontent.com/16075710/154289437-6eeaab02-6d1d-4b89-a7e5-57ef69beef6f.jpg)

**Comment by larrinator1** [comment]
Yes, go to https://anchor.so/errors
