### ISSUE TITLE
calculateRewardsEarned 

### ISSUE THREAD

**Issue by halimabergaoui** [QuarryProtocol/quarry#448]
Hello,

How can I get the reward amount of a given user? I tried using calculateRewardsEarned function but I am getting a very large number. Is it the problem that I am using the wrong function or there is a missing integer conversion?

**Comment by larrinator1** [comment]
What number do you expect?

**Comment by halimabergaoui** [comment]
I am expecting about 0.000031 from the pool usdc/usdt

**Comment by halimabergaoui** [comment]
this is solved. the problem was in the timestamp should be in seconds.
