### ISSUE TITLE
Generate idl types doesn't work on OSX

### ISSUE THREAD

**Issue by beautyfree** [QuarryProtocol/quarry#97]
Generation on OSX causes wrong types:
```
export type UquarryUmineIDL = {
```

Line with problem https://github.com/QuarryProtocol/quarry/blob/v1.6.5/scripts/generate-idl-types.sh#L13-L17

Reference with answer why https://stackoverflow.com/questions/1538676/uppercasing-first-letter-of-words-using-sed#comment51846289_1538818

**Comment by michaelhly** [comment]
Please install gnu-sed on osx with `brew install gnu-sed`.
